/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Matteo
 * Created: 21-mag-2016
 */

CREATE TABLE utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    saldo DOUBLE PRECISION,
    tipo INTEGER /* Vale 0 per venditore, 1 per cliente */
);

CREATE TABLE prodotti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    url_immagine VARCHAR(128),
    descrizione VARCHAR(200),
    prezzo DOUBLE PRECISION,
    quantita INTEGER,
    venditore_id INTEGER,
    FOREIGN KEY (venditore_id) REFERENCES utenti(id)
)