/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Matteo
 * Created: 21-mag-2016
 */

CREATE TABLE utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    saldo DOUBLE PRECISION,
    tipo INTEGER /* Vale 0 per venditore, 1 per cliente */
);

CREATE TABLE prodotti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    url_immagine VARCHAR(128),
    descrizione VARCHAR(200),
    prezzo DOUBLE PRECISION,
    quantita INTEGER,
    venditore_id INTEGER,
    FOREIGN KEY (venditore_id) REFERENCES utenti(id)
)

INSERT INTO utenti (id, username, password, saldo, tipo)
VALUES (default, 'Vend1', '0', 10, 0);

INSERT INTO utenti (id, username, password, saldo, tipo)
VALUES (default, 'Cli1', '0', 7, 1);

INSERT INTO utenti (id, username, password, saldo, tipo)
VALUES (default, 'Vend2', '0', 14, 0);

INSERT INTO utenti (id, username, password, saldo, tipo)
VALUES (default, 'Cli2', '0', 20, 1);

INSERT INTO utenti (id, username, password, saldo, tipo)
VALUES (default, 'Cli3', '0', 8, 1);

INSERT INTO prodotti (id, nome, url_immagine, descrizione, prezzo, quantita, venditore_id)
VALUES (default, 'Grattaschiena', 'img/grattaschiena.jpg', 'Un grattaschiena', 4, 5, 1);

INSERT INTO prodotti (id, nome, url_immagine, descrizione, prezzo, quantita, venditore_id)
VALUES (default, 'Carriola', 'img/carriola.jpg', 'Una carriola', 5, 6, 1);

INSERT INTO prodotti (id, nome, url_immagine, descrizione, prezzo, quantita, venditore_id)
VALUES (default, 'Frullatore', 'img/frullatore.jpg', 'Un frullatore', 6, 7, 3);

INSERT INTO prodotti (id, nome, url_immagine, descrizione, prezzo, quantita, venditore_id)
VALUES (default, 'Sedia', 'img/sedia.jpg', 'Una sedia', 7, 8, 3);

INSERT INTO prodotti (id, nome, url_immagine, descrizione, prezzo, quantita, venditore_id)
VALUES (default, 'Foglio', 'img/foglio.jpg', 'Un foglio', 8, 9, 1);